# Generated by Django 4.2.30 on 2026-07-31 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="is_duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_deals",
                to="crm.contact",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="source_branch_requested",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="source_city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
