# Generated by Django 4.2.30 on 2026-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_deal_is_duplicate_of_deal_source_branch_requested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
