// frontend/src/types.ts

export type PipelineId = 'school' | 'kindergarten' | 'b2b';
export type DealStageId = string;
export type Branch = {
  id: string;
  name: string;
  code?: string;
  city?: string;
  segment?: string;
  is_free?: boolean;
  subsidy_amount?: string;
}
export type Tariff = {
  id: string;
  name: string;
  branchCode: string;
  grade_band: string;
  base_amount: number;
  entrance_fee: number;
}

// --- РОЛЕВАЯ МОДЕЛЬ (RBAC, раздел 8.1) ---
export type UserRole = 'HQ_ADMIN' | 'BRANCH_DIRECTOR' | 'SALES_MANAGER';

export interface CurrentUser {
  id: number | string;
  username: string;
  email?: string;
  first_name?: string;
  last_name?: string;
  role: UserRole;
  branch: Branch | null; // null только для HQ_ADMIN
}

// --- СУЩНОСТИ CRM ---
export interface Parent {
  id: string;
  name: string;
  phone: string;
  iin?: string;
  email?: string;
}

export type GradeBand = 'PRESCHOOL' | 'PRIMARY_SECONDARY' | 'SENIOR';

export interface Child {
  id: string;
  parentId: string;
  name: string;
  birthDate?: string;
  gradeOrGroup: string; // Например: "1А", "Средняя группа"
  gradeBand?: GradeBand; // 0 класс, 1-11 классы, 12 класс
  isSecondChild?: boolean; // Для расчета скидки 10% в детских садах
  allergies?: string;
}

export interface ActivityLog {
  id: string;
  type: string;
  description: string;
  timestamp: string;
}

export interface Task {
  id: string;
  title: string;
  isDone: boolean;
  dueDate: string;
  autoGenerated?: boolean;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH';
  isCompleted?: boolean;
  assigned_to?: number | string | null;
}

export interface PaymentScheduleEntry {
  id: string;
  title: string;
  due_date: string;
  amount: string;
  status: 'PENDING' | 'PAID' | 'OVERDUE';
}

export interface B2BInfo {
  companyName?: string;
  bin?: string;
  contactPerson?: string; // ФИО, должность
  position?: string;
  phone?: string;
  email?: string;
  serviceType?: string; // Франчайзинг | Строительство | Консалтинг | Управление
  budget?: number;
}

export interface Deal {
  id: string;
  parent: Parent;
  child: Child;
  paymentSchedule?: PaymentScheduleEntry[];
  branchId: string;
  /** Отображаемые названия (из ответа бэкенда) — чтобы не зависеть от mockBranches/mockTariffs */
  branchName?: string;
  tariffName?: string;
  pipelineId: PipelineId;
  stageId: DealStageId;
  status: 'ACTIVE' | 'WON' | 'LOST' | 'WAITLIST';
  tariffId: string;
  hasFood: boolean;
  hasTransport: boolean;
  totalAmount: number;
  expectedRevenue: number;
  tasks: Task[];
  history: ActivityLog[];
  addons: {
    food: boolean;
    transport: boolean;
  };
  isWaitlisted: boolean;
  waitlistPosition?: number;
  // Гео-роутинг (раздел 8.5) + анти-дубль (раздел 7, Риск 4)
  sourceCity?: string;
  sourceBranchRequested?: string;
  isCrossBranch?: boolean;
  isDuplicateOf?: string | null;
  contactId?: string; // id существующего Contact при анти-дубль привязке
  // B2B (раздел спецификации: партнёрские/франчайзинговые сделки)
  b2b?: B2BInfo;
  partnerType?: string;
  contractValue?: number;
}

// --- НАСТРОЙКИ КАНБАН-ДОСКИ ---

// Массив со списком воронок
export const pipelines = [
  { id: 'school', name: 'B2C Частные Школы' },
  { id: 'kindergarten', name: 'B2C Детские Сады' },
  { id: 'b2b', name: 'B2B Партнерства' },
];

// Порядок стадий (колонок) для каждой воронки
export const pipelineStageOrder: Record<PipelineId, DealStageId[]> = {
  school: [
    'new', // Неразобранное
    'tour_scheduled', // Экскурсия/тест назначены
    'tariff_selected', // Выбор тарифа
    'contract_signed', // Договор подписан
    'entrance_fee_paid', // Взнос оплачен
    'enrolled' // Зачислен (Успешно)
  ],
  kindergarten: [
    'new', // Первичный контакт
    'trial_scheduled', // Запись на пробный день
    'adaptation', // Адаптация
    'entrance_fee_paid', // Взнос оплачен
    'first_month_paid', // Оплата 1 месяца
    'enrolled' // Зачислен
  ],
  b2b: [
    'new', // Первичный контакт
    'meeting', // Встреча
    'commercial_offer', // КП
    'contract_negotiation', // Согласование
    'invoice_sent', // Счет выставлен
    'won' // Закрыто
  ]
};

// Красивые названия стадий для отображения в интерфейсе
export const stageLabels: Record<string, string> = {
  new: 'Неразобранное / Первичный контакт',
  tour_scheduled: 'Экскурсия/тест назначены',
  tariff_selected: 'Выбор тарифа и доп. услуг',
  contract_signed: 'Договор подписан',
  entrance_fee_paid: 'Взнос оплачен',
  enrolled: 'Зачислен (Успешно)',
  trial_scheduled: 'Запись на пробный день',
  adaptation: 'Адаптация',
  first_month_paid: 'Оплата 1-го месяца',
  meeting: 'Встреча',
  commercial_offer: 'Коммерческое предложение',
  contract_negotiation: 'Согласование договора',
  invoice_sent: 'Счет выставлен',
  won: 'Сделка заключена'
};

// Красивые названия воронок
export const pipelineLabels: Record<PipelineId, string> = {
  school: 'B2C Частные Школы',
  kindergarten: 'B2C Детские Сады',
  b2b: 'B2B Партнерства'
};